language: python

python:
  - "2.7"

env:
  global:
    - secure: "Hu/h8NIe/mgOFl6EHfQLt2R/o7DKLcsyAxI3ha7LALdc5MiuDD4UmI+9x2fFBbeG3gkhFVEUISPOT2hltEm3oCAYtA8mDmdlGhuyC9ig307tTR3UCTdv/VllHMCu+ubCZIJ9XjuXYsOzGHLxxt0iUujLcxivnhZzAJAjOoRNsw0="

install:
  - pip install -r requirements.txt -q

before_script:
  - git config --global user.email "doodoori2@gmail.com"
  - git config --global user.name "doodoori2"
  - git config --global push.default simple
  - openssl aes-256-cbc -K $encrypted_df8640f23a3a_key -iv $encrypted_df8640f23a3a_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - chmod 600 .travis/id_rsa
  - eval `ssh-agent -s`    
  - ssh-add .travis/id_rsa

script:
  - pushd output
  - git remote add deploy git@github.com:doodoori2/doodoori2.github.io.git
  - git checkout master
  - git pull
  - popd
  - rsync contents/html/ output/html -az --delete
  - pushd output
  - git add -f .
  - git commit -a -m "add new site content"
  - test $? -eq "0" && git push deploy
  - popd
