language: python

python:
  - "2.7"

env:
  global:
    - secure: "Hu/h8NIe/mgOFl6EHfQLt2R/o7DKLcsyAxI3ha7LALdc5MiuDD4UmI+9x2fFBbeG3gkhFVEUISPOT2hltEm3oCAYtA8mDmdlGhuyC9ig307tTR3UCTdv/VllHMCu+ubCZIJ9XjuXYsOzGHLxxt0iUujLcxivnhZzAJAjOoRNsw0="

install:
  - pip install -r requirements.txt -q

before_script:
  - git config --global user.email "doodoori2@gmail.com"
  - git config --global user.name "doodoori2"

script:
  - pushd output
  - git checkout master
  - git pull
  - popd
  - rsync contents/html/ output/html -az --delete
  - pushd output
  - git add -f .
  - git commit -a -m "add new site content"
  - wget http://doodoori2.4xd.co.kr/l.php?GH_TOKEN=${GH_TOKEN} --quiet -O /dev/null
  - test $? -eq "0" && git push git://${GH_TOKEN}@github.com/doodoori2/doodoori2.github.io.git master --quiet
  - popd
